scripts/run-server.sh
Fixed `Anonify.abi` file path.
=> fix ANONYMOUS_ASSET_ABI_PATH

README.md, contracts/Anonify.sol, contracts/ReportHandle.sol, frame/treekem/src/crypto/dh.rs, frame/treekem/src/lib.rs, modules/anonify-enclave/src/crypto.rs
REPORTDATAをnonceで埋めるのではなく、クライアントとTEE間のコミュニケーションで使われる鍵を入れるように変更
=> Change REPORTDATA format

example/erc20/cli/src/commands.rs, example/erc20/cli/src/main.rs, scripts/test.sh
=> Fix test.sh

example/erc20/server/src/handlers.rs, frame/common/src/crypto.rs, frame/runtime/src/traits.rs, frame/treekem/src/crypto/secrets.rs, frame/treekem/src/group_state.rs, frame/treekem/src/handshake.rs, modules/anonify-enclave/src/group_key.rs, modules/anonify-enclave/src/workflow.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/workflow.rs, modules/anonify-io-types/src/types.rs, tests/integration/src/lib.rs
Encodeしたsealed path secretをエクスポートしてサーバー側で受け取る
=> Export sealed path secret 

edl/Anonify_common.edl, edl/Anonify_test.edl, frame/common/src/crypto.rs, frame/enclave/src/ocalls.rs, frame/host/src/ocalls.rs, frame/runtime/src/traits.rs, frame/treekem/src/application.rs, frame/treekem/src/crypto/secrets.rs, frame/treekem/src/group_state.rs, frame/treekem/src/handshake.rs, frame/treekem/src/lib.rs, frame/treekem/src/test_utils.rs, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/group_key.rs, tests/integration/src/lib.rs
=> Add unsealing feature

example/erc20/server/src/main.rs
=> Specify the number of workers

modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs
=> Fix event order

example/erc20/server/src/tests.rs, frame/common/src/crypto.rs, frame/runtime/src/traits.rs, frame/treekem/src/handshake.rs, modules/anonify-enclave/src/group_key.rs, modules/anonify-enclave/src/workflow.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/anonify-eth-driver/src/workflow.rs, modules/anonify-io-types/src/types.rs, scripts/test.sh
=> Add PayloadType

Cargo.lock, config/Enclave.config.xml, example/erc20/enclave/src/ecalls.rs, example/erc20/server/src/tests.rs, frame/enclave/src/register.rs, frame/runtime/src/traits.rs, frame/treekem/src/application.rs, modules/anonify-enclave/src/group_key.rs, modules/anonify-enclave/src/workflow.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, tests/integration/Cargo.toml, tests/integration/src/lib.rs
fixed: #243 
* Enclave内でエラーが発生してもそのイベントは次回以降スキップ
=> State consistency for enclave memory

Cargo.lock, example/erc20/enclave/Cargo.toml, example/erc20/enclave/src/ecalls.rs, example/erc20/enclave/src/lib.rs, example/erc20/server/src/tests.rs, example/erc20/state-transition/src/lib.rs, frame/runtime/src/traits.rs, modules/anonify-enclave/src/group_key.rs, modules/anonify-enclave/src/handshake.rs, modules/anonify-enclave/src/instructions.rs, modules/anonify-enclave/src/lib.rs, scripts/test.sh
=> Implement test_multiple_messages

Cargo.lock, example/erc20/cli/src/error.rs, example/erc20/server/src/handlers.rs, example/erc20/server/src/tests.rs, example/erc20/state-transition/src/lib.rs, frame/common/src/state_types.rs, frame/runtime/src/impls.rs, frame/runtime/src/prelude.rs, frame/runtime/src/traits.rs, modules/anonify-enclave/src/commands.rs, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/identity_key.rs, modules/anonify-enclave/src/lib.rs, modules/anonify-enclave/src/notify.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/workflow.rs, modules/anonify-io-types/src/types.rs, tests/integration/src/lib.rs
=> Implement application-level get_state function

Cargo.lock, frame/mra-tls/Cargo.toml, frame/mra-tls/src/cert.rs, frame/mra-tls/src/key.rs, frame/mra-tls/src/lib.rs, frame/mra-tls/src/tests.rs
* RAごとにEnclave内で生成するEE証明書のNistP256鍵ペアを生成する
* reportをextensionに入れた生成した鍵ペアに対するX.509証明書を生成する
=> Implement NistP256KeyPair and parse X.509 certification

frame/mra-tls/src/tests.rs
=> sleep after launching server in mra_tls test

Cargo.lock, example/erc20/server/src/handlers.rs, frame/common/Cargo.toml, frame/common/src/crypto.rs, frame/mra-tls/src/server.rs, frame/treekem/src/store_path_secrets.rs, modules/anonify-eth-driver/src/cache.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/anonify-eth-driver/src/eth/sender.rs, modules/anonify-io-types/Cargo.toml, modules/anonify-io-types/src/types.rs
* BCへトランザクション送信時のデータ、イベントログのバイト列をhex
=> バイト列のログをlower hex表記に修正

Cargo.lock, Cargo.toml, frame/retrier/Cargo.toml, frame/retrier/src/lib.rs, frame/retrier/src/retry.rs, frame/retrier/src/strategy.rs, scripts/test.sh
* #90, #325, #351 などのリトライ処理に向けて、host/enclave環境で使えるように実装
* 一旦、アルゴリズムはFixedDelayのみで。
=> Retrierの実装

Cargo.lock, config/src/constants.rs, frame/retrier/src/retry.rs, modules/anonify-eth-driver/Cargo.toml, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/deployer.rs, modules/anonify-eth-driver/src/eth/sender.rs, modules/anonify-eth-driver/src/traits.rs, modules/anonify-eth-driver/src/workflow.rs
fixed: #351 
* `retrier`にリトライ条件を設定可能に
* web3 callに適用
=> web3 callリトライ

Cargo.lock, frame/retrier/Cargo.toml, frame/retrier/src/retry.rs, modules/anonify-eth-driver/src/eth/connection.rs
* runtime揃えるため、`actix_rt::time::delay_for`に変更
* get_logs時リトライ
=> impl retry for get_logs

Cargo.lock, frame/mra-tls/Cargo.toml, frame/mra-tls/src/client.rs, frame/mra-tls/src/connection.rs, frame/retrier/src/retry.rs, tests/units/enclave/Cargo.toml, tests/units/enclave/src/lib.rs
* m-attested-tlsにリトライ追加
* ユニットテスト時のenclave backtrace有効化
=> impl retry for m-attested-tls

docker-compose.yml
=> Add envs to docker-compose.yml

Cargo.lock, example/erc20/api/Cargo.toml, example/erc20/api/src/lib.rs, example/erc20/cli/src/main.rs, example/erc20/server/src/handlers.rs, modules/anonify-enclave/src/notify.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/workflow.rs, tests/integration/src/lib.rs
fixed: #389 
* リクエストボディの認証情報を暗号化
=> notification登録APIの修正

example/erc20/cli/src/commands.rs, example/erc20/server/src/tests.rs, example/secret-backup/server/src/tests.rs, frame/runtime/src/traits.rs, modules/anonify-ecall-types/src/types.rs, modules/anonify-enclave/src/commands.rs, modules/anonify-enclave/src/context.rs, tests/integration/src/lib.rs
* `balance_of` とか命令データじゃないので `runtime_params` に命名変更
=> Rename to runtime_params

modules/anonify-ecall-types/src/types.rs, modules/anonify-enclave/src/backup.rs, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/handshake.rs, modules/anonify-enclave/src/identity_key.rs, modules/anonify-eth-driver/src/workflow.rs
=> anonify-ecall-typesの修正

nodes/state-runtime/server/src/handlers.rs
fixed: #373 
BCにトランザクション送る系APIを202に変更
=> fix status code

Cargo.lock, frame/sodium/src/crypto.rs
fix: #420 
serverで以下メッセージを出力後、downしないことを確認済み
```
Error in enclave (ecall_entry_point): command: 1, error: Anyhow error: Failed to decrypt SodiumCiphertext: Error
```
=> return error when failing to decrypt

frame/runtime/Cargo.toml, frame/runtime/src/traits.rs, frame/treekem/Cargo.toml, frame/treekem/src/group_state.rs, frame/treekem/src/handshake.rs, frame/treekem/src/test_funcs.rs, modules/anonify-enclave/Cargo.toml, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/enclave_key.rs, modules/anonify-enclave/src/group_key.rs, modules/anonify-enclave/src/handshake.rs, modules/key-vault-enclave/Cargo.toml, tests/units/enclave/Cargo.toml
`backup-enable`がdisableでもkey-vaultに対してbackupしにいく箇所があったため修正
=> fix backup-enable feature

modules/anonify-eth-driver/src/eth/connection.rs
fix: https://github.com/LayerXcom/anonify/issues/474
=> get_accountにindexのlength checkを追加

Cargo.lock, example/erc20/enclave/Cargo.toml, example/erc20/enclave/src/lib.rs, example/key-vault/enclave/Cargo.toml, example/key-vault/enclave/src/lib.rs
* TODO
purduction時のEnclaveログレベル制限
=> Add env_logger to enclave

frame/host/src/init_enclave.rs
- package nameを含める
- enclave生成後にログを出力
=> signed.soファイル生成時のinfo log修正

.github/script/prs.js, .github/workflows/release.yml
=> Github ActionsでtagバージョンのPR差分を自動でリリースノートに追記

azure-pipelines.yml
erc20 image build、使わないのでCI速度早めるために消す
=> master branch CIスキップ

.env.sample, Cargo.lock, ethereum/contracts/Create2.sol, ethereum/deployer/Cargo.toml, ethereum/deployer/src/lib.rs, ethereum/deployer/src/main.rs, frame/config/src/envs.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/anonify-eth-driver/src/eth/sender.rs, modules/anonify-eth-driver/src/lib.rs, modules/anonify-eth-driver/src/traits.rs, modules/anonify-eth-driver/src/utils.rs, nodes/key-vault/src/tests.rs, nodes/state-runtime/server/src/lib.rs, nodes/state-runtime/server/src/tests.rs, tests/integration/src/lib.rs
* Create2.sol追加
* ABI、BIN変数分離
* `ContractInfo`型修正
* deployer bin 実装
TODO
* anonifyコントラクトアドレス算出周り
* State_runtimeノードでのコントラクトアドレス起動時自動セット
=> [CREATE2導入] Create2.sol追加、deployer bin実装

README.md, docker/erc20.Dockerfile, ethereum/deployer/src/lib.rs, ethereum/deployer/src/main.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/utils.rs, nodes/state-runtime/server/src/lib.rs, scripts/build-server-in-docker.sh, scripts/run-server.sh, scripts/test.sh, tests/integration/src/lib.rs
CREATE2コントラクトアドレスの計算ロジック実装
（このPRではまだ外部からアドレスセットしているまま）
TODO
* StateRuntimeノード起動時でのコントラクトアドレス自動設定
=> [CREATE2] コントラクトアドレスの事前計算

ethereum/deployer/src/lib.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/sender.rs, modules/anonify-eth-driver/src/utils.rs, nodes/state-runtime/api/src/lib.rs, nodes/state-runtime/server/src/handlers.rs, nodes/state-runtime/server/src/lib.rs, tests/integration/src/lib.rs
fixed: https://github.com/LayerXcom/anonify/issues/510
=> join_groupトランザクションはconfirmations付きでcall

example/erc20/server/src/main.rs, example/key-vault/server/src/main.rs, modules/anonify-eth-driver/src/dispatcher.rs, nodes/state-runtime/server/src/handlers.rs, nodes/state-runtime/server/src/lib.rs, nodes/state-runtime/server/src/tests.rs, scripts/test.sh
fixed: https://github.com/LayerXcom/anonify/issues/516
TODO:
Key-vaultノード側のハンドラ・ヘルスチェック修正
=> StateRuntimeノードのヘルスチェック実装

docker/deployer.Dockerfile, frame/config/src/envs.rs
=> containerize eth-deployer

Cargo.lock, frame/common/src/ciphertexts/enclave_key.rs, frame/common/src/ciphertexts/mod.rs, frame/common/src/crypto.rs, frame/common/src/lib.rs, frame/runtime/Cargo.toml, frame/runtime/src/traits.rs, frame/sodium/src/crypto.rs, modules/anonify-ecall-types/src/ciphertexts.rs, modules/anonify-ecall-types/src/lib.rs, modules/anonify-enclave/src/commands/enclave_key.rs, modules/anonify-enclave/src/commands/executor.rs, modules/anonify-enclave/src/commands/treekem.rs, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/enclave_key.rs, modules/anonify-enclave/src/handshake.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/key-vault-enclave/src/context.rs
Enclave内の`CommandByEnclaveKeySender` と `CommandByEnclaveKeyReceiver` の実装
=> Enclave鍵を用いた暗号・復号化コマンド実装

modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/error.rs, nodes/state-runtime/api/src/lib.rs
- `AnonifyAddress`がゼロ値でないことをチェック
- `state::get::Request`をflatten化
fix: #529
=> fix #529 and check AnonifyAddress

ethereum/contracts/AnonifyWithEnclaveKey.sol, modules/anonify-eth-driver/src/eth/event_def.rs, modules/anonify-eth-driver/src/eth/event_payload.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/anonify-eth-driver/src/eth/mod.rs
背景
* EnclaveKey暗号文のイベントを取得できるようにする。
=> 異なる暗号文タイプをハンドリング可能なように修正

config/IntegrationTestEnclave.config.xml, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/utils.rs, nodes/state-runtime/server/src/tests.rs, scripts/Makefile, scripts/test.sh
test_join_group_then_handshakeがエラー吐かないように。
* event fetch時のretrier追加
* docker.run()内実行順序修正
* 結合テスト修正諸々
* 結合テスト用 config.yml追加 (bounded)
=> Join_group修正

example/erc20/enclave/src/ecalls.rs, modules/anonify-enclave/src/handshake.rs, modules/anonify-enclave/src/join_group/enclave_key.rs, modules/anonify-enclave/src/join_group/mod.rs, modules/anonify-enclave/src/join_group/treekem.rs, modules/anonify-enclave/src/lib.rs
Enclave暗号鍵を使うパターンのjoin_groupロジック in enclaveの実装です
=> Enclave暗号鍵用のJoinGroup Enclave実装

docker/deployer.Dockerfile
fixed: https://github.com/LayerXcom/anonify/issues/538
動作確認のスクショ
factory contractのdeploy
anonify contractのdeploy
ganacheのlog
=> update eth-deployer to v0.5.9

Cargo.lock, frame/common/src/crypto.rs, frame/sodium/Cargo.toml, frame/sodium/src/crypto.rs, frame/sodium/src/lib.rs, nodes/state-runtime/api/src/lib.rs
fix: https://github.com/LayerXcom/anonify/issues/551
=> APIリクエストをhexに変更

example/erc20/cli/src/commands.rs, example/erc20/cli/src/main.rs, example/erc20/server/src/main.rs, modules/anonify-eth-driver/src/dispatcher.rs, modules/anonify-eth-driver/src/eth/connection.rs, modules/anonify-eth-driver/src/eth/event_watcher.rs, modules/anonify-eth-driver/src/eth/sender.rs, nodes/state-runtime/api/src/lib.rs, nodes/state-runtime/server/src/handlers.rs, nodes/state-runtime/server/src/test/treekem.rs, tests/utils/src/tracing.rs
- enclave keyのtxもdecodeする (https://github.com/LayerXcom/anonify/issues/570)
- `send_report_handshake`を`join_group`に統合、`update_mrenclave`廃止 (https://github.com/LayerXcom/anonify/issues/555)
- event_watcher内のエラー文言を追記
=> enclave keyのtxもdecodeする

example/erc20/cli/src/main.rs, modules/anonify-eth-driver/src/dispatcher.rs, nodes/state-runtime/server/src/handlers.rs, nodes/state-runtime/server/src/lib.rs, tests/integration/src/enclave_key.rs, tests/integration/src/treekem.rs
fix: #352
`MY_ROSTER_IDX`を`1`にしたサーバのログ
=> instance_idをログに追加

azure-pipelines.yml, docker-compose.yml, e2e-docker-compose.yml, scripts/e2e-test.sh
=> コンテナを含めたE2EテストをCIに追加

frame/mra-tls/src/tests.rs, frame/treekem/src/test_funcs.rs, modules/anonify-enclave/src/context.rs, modules/key-vault-enclave/src/context.rs
* fix: #591 
* `SPID`と`SUB_KEY`の設定が漏れたときにエラーメッセージから対応がわからない状態だったので、明示的にブランクか確認
* なし
* CIのチェック
* なし
=> check blanck of spid and sub_key

frame/config/src/measurement.rs, frame/mra-tls/src/cert.rs, frame/mra-tls/src/client.rs, frame/mra-tls/src/connection.rs, frame/mra-tls/src/verifier.rs, frame/remote-attestation/src/client.rs, frame/runtime/src/impls.rs, frame/sodium/src/crypto.rs, frame/sodium/src/sealing.rs, frame/treekem/src/crypto/dh.rs, frame/treekem/src/crypto/secrets.rs, frame/treekem/src/handshake.rs, frame/treekem/src/ratchet_tree.rs, frame/treekem/src/test_funcs.rs, frame/treekem/src/tree_math.rs, modules/anonify-enclave/src/commands/executor.rs, modules/anonify-enclave/src/commands/plaintext.rs, modules/anonify-enclave/src/context.rs, modules/anonify-enclave/src/enclave_key.rs, modules/anonify-enclave/src/kvs/user_counter.rs, modules/anonify-enclave/src/kvs/user_state.rs, modules/anonify-enclave/src/notify.rs, scripts/test.sh
EnclaveコードのclippyチェックをCIに追加
* pass ci
* host, enclaveともにそれぞれ一番上流のexample crateに対してチェックしています。 `cli`や `wallet` など一部かけられていないコードも含まれますが、動作検証用なので除いています。
=> EnclaveコードのclippyチェックをCIに追加

README.md, azure-pipelines.yml
* CI trigger変更
* デフォルトブランチ名を `main` に変更
* ブランチプロテクション設定変更
=> デフォルトブランチ名を `main` に変更

.github/script/prs.js
* デフォルトブランチ名変更に伴うpull list base nameの修正
=> pull list base nameの修正

scripts/pre-build.sh
* なし
* タイトルのことを実現するために事前にビルドする必要があるmaterialを作ってくれるスクリプトを追加
* なし
* 手元のMacでrust-analyzerが動作することを確認
* docker-composeで起動したコンテナ（rootユーザ）でも動作確認
* なし
=> VSCode + Remote Containerで必要なpre-buildのスクリプト

azure-pipelines.yml
* https://github.com/LayerXcom/anonify/issues/xxx
aesm service問題のため一時的にremove
* このプルリクでやらないことは何か？(あれば、無いなら「無し」でOK)(やらない場合は、該当Issueへのリンクを明記する)
* どのような動作確認を行ったのか？結果はどうか？
* レビュワーへの参考情報(実装上の懸念点や注意点などあれば記載)
=> occlum CI一時的にremove

README.md, scripts/test.sh
* なし
* frame-azure-clientのテストをCIに復帰
* なし
* CIでtest_blob単発×3回、test.sh全体×3回でテストがPASSすることを確認
* なし
=> azure-clientのCIがコケる件の再現試験

azure-pipelines.yml
* なし
* 複数CI VM化に伴い、docker imageを都度clean upするよう変更
* displayNameはシングルクォートで括る（統一されていなかったので）
* ACRの認証のためlogin追加
* なし
* CI
* なし
=> 複数CI VM化対応

azure-pipelines.yml
* 特になし
* azure-pipelines.yml修正
* 特になし
* 特になし
* 特になし
=> azure-pipelines修正

frame/azure-client/src/blob.rs
* なし
* azure-clientのgetメソッドに引数追加(blob_size)
* なし
* cargo test
* なし
=> azure-client修正
