LayerXcom/anonify

example/erc20/api/src/lib.rs
example/erc20/enclave/src/ecalls.rs
example/erc20/server/src/handlers.rs
example/erc20/state-transition/src/lib.rs
example/invoice-flow/enclave/src/ecalls.rs
example/invoice-flow/server/src/handlers.rs
example/invoice-flow/state-transition/src/lib.rs
frame/common/src/crypto.rs
frame/common/src/state_types.rs
frame/common/src/traits.rs
frame/runtime/src/impls.rs
frame/runtime/src/prelude.rs
frame/runtime/src/primitives.rs
frame/runtime/src/traits.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/crypto.rs
modules/anonify-enclave/src/instructions.rs
modules/anonify-enclave/src/kvs/mod.rs
modules/anonify-enclave/src/notify.rs
modules/anonify-enclave/src/workflow.rs
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/eth/client.rs
modules/anonify-eth-driver/src/traits.rs
modules/anonify-eth-driver/src/utils.rs
modules/anonify-eth-driver/src/workflow.rs
modules/anonify-io-types/src/types.rs
tests/integration/src/lib.rs
wallet/src/keyfile.rs

* 元の`AccessRight` structを`Ed25519ChallengeResponse` に変更
* 命名：`address`を`account_id`に統一変更
* `AccessPolicy` traitを実装し、検証部分を抽象化

Implement AccessPolicy

---

contracts/Anonify.sol
contracts/utils/BytesUtils.sol

resolved: #91 
* roster indexは環境変数により指定し、他のTEEと被る値を設定するとhandshake process時に上書きされたTEEでエラーが発生してしまう
* このエラーは上書き以降のpath secretが異なるために生じるものであり、それ以降の暗号文が復号できなくなる
* コントラクトでhandshake payloadに含まれるroster idxを用いてバリデーションを追加

Add roster index velidations

---

Cargo.lock
example/secret-backup/server/src/tests.rs
scripts/test.sh

- localにpath secretがなく、remoteにもない場合はエラーが発生するテストを追加
※`libc::shutdown`の実装がうまくいかなかったので、`cargo test`をtest関数ごとに書いてます。

add key-vault test

---

Cargo.lock
example/secret-backup/server/Cargo.toml
example/secret-backup/server/src/tests.rs

key-vault serverが落ちている状態でもlocalからpath_secretが復元できることのテストを追加
key-vault serverは`sgx_urts::rsgx_destroy_enclave`で落とした。

add test to recover path_secret even if key-vault server is down

---

Cargo.lock
edl/Anonify_common.edl
frame/remote-attestation/Cargo.toml
frame/remote-attestation/src/client.rs
frame/remote-attestation/src/error.rs
frame/retrier/src/retry.rs
modules/anonify-eth-driver/src/eth/deployer.rs
modules/anonify-eth-driver/src/eth/sender.rs

* remote-attestationにリトライ実装
500, 503のとき、IoErrorのときはリトライ
* リトライ条件をエラー時だけでなく、ステータスコードなどで設定可能に
* remote attestationレスポンスのステータスコード検証追加

Implement retry to remote-attestation

---

Cargo.lock
config/src/lib.rs
example/erc20/enclave/Cargo.toml
example/erc20/enclave/src/lib.rs
example/secret-backup/enclave/Cargo.toml
example/secret-backup/enclave/src/lib.rs
frame/config/src/envs.rs
frame/runtime/src/traits.rs
frame/treekem/src/group_state.rs
frame/treekem/src/handshake.rs
frame/treekem/src/test_funcs.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/group_key.rs
modules/anonify-enclave/src/handshake.rs
tests/units/enclave/Cargo.toml
tests/units/enclave/src/lib.rs

* Key-Vaultノードでへのリカバリリクエストを `AnonifyContext` に実装（ClientConfigが毎回使いまわせる）
* `ENCLAVE_SIGNED_SO`などanonify-configから削除

Implement recover request to key-vault node for AnonifyContext

---

example/erc20/api/src/lib.rs
example/erc20/cli/src/commands.rs
example/erc20/server/src/handlers.rs
example/erc20/server/src/main.rs
example/erc20/server/src/tests.rs
example/secret-backup/server/src/tests.rs

related: #379 
* (POST) `api/v1/state` に実行する状態遷移関数 `function` のパラメタを含めて定義

状態遷移APIの一般化

---

Cargo.lock
example/erc20/cli/Cargo.toml
example/erc20/cli/src/commands.rs
example/erc20/state-transition/src/lib.rs
frame/runtime/src/impls.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/handshake.rs
modules/anonify-eth-driver/src/workflow.rs
tests/integration/Cargo.toml
tests/integration/src/lib.rs

* anonify-ecall-typesを使わずjsonのみでreq表現 in CLI
* state-transitionからfn_id消去
* 命名：`fn_name`から`cmd_name`へ変更

クライアントリクエストをjson化 (send_command)

---

Cargo.lock
example/erc20/api/Cargo.toml
example/erc20/api/src/lib.rs
example/erc20/cli/src/commands.rs
example/erc20/cli/src/main.rs
example/erc20/server/src/handlers.rs
example/erc20/server/src/main.rs
example/erc20/server/src/tests.rs
example/erc20/state-transition/Cargo.toml
example/erc20/state-transition/src/lib.rs
example/secret-backup/server/src/tests.rs
frame/common/src/state_types.rs
frame/common/src/traits.rs
frame/runtime/src/impls.rs
frame/runtime/src/lib.rs
frame/runtime/src/prelude.rs
frame/runtime/src/primitives.rs
frame/runtime/src/traits.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/context.rs
modules/anonify-eth-driver/Cargo.toml
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/error.rs
modules/anonify-eth-driver/src/workflow.rs
tests/integration/src/lib.rs

fixed: #379 , fixed: #395 , fixed: #388
* 状態データ取得系エンドポイントを`GET: /api/v1/state`に統一
* リクエストボディにruntimeパラメタを導入し、状態取得時にロジック実行可能に ( `allowance`の`spender`などで `BtreeMap`が返ってくるのではなくvalueの`U64`がレスポンス）
* `GET: /api/v1/state` のリクエストボディ暗号化（認証情報&状態データ名&runtimeパラメタ）
TODO
* notificationの型の一般化
```
server
.dispatcher
.fetch_events::<U64>(FETCH_CIPHERTEXT_CMD, FETCH_HANDSHAKE_CMD)
```
* `get_state`, `send_command` 以外のリクエストボディの暗号化
* サーバー部分のmodule移行 (#402)
* rename: `runtime_cmd` -> `runtime_params`

`GET: /api/v1/state` のアップデート

---

Cargo.lock
example/erc20/enclave/src/ecalls.rs
example/erc20/server/Cargo.toml
example/erc20/server/src/handlers.rs
example/erc20/state-transition/src/lib.rs
frame/common/Cargo.toml
frame/common/src/lib.rs
frame/common/src/state_types.rs
frame/runtime/src/impls.rs
frame/runtime/src/traits.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/lib.rs
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/eth/event_watcher.rs
modules/anonify-eth-driver/src/traits.rs
modules/anonify-eth-driver/src/workflow.rs
tests/integration/src/lib.rs

* 状態遷移の型が分かる段階でserializeしないといけないので、新たに `UpdatedState`の他に `NotifyState`定義しています
* `UpdatedState`は バイナリエンコードされる一方、 `NotifyState` は jsonエンコードした上でバイナリエンコードしています。
*  状態型が`Approved`の場合はNotificationスキップ （`BTreeMap`のキーがnot `String`の場合 `Serde_json::to_value()`できないため）（#414）

Notification to host agentの一般化実装

---

Cargo.lock
contracts/Anonify.sol
frame/common/src/state_types.rs
frame/runtime/src/traits.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/handshake.rs
modules/anonify-eth-driver/src/cache.rs
modules/anonify-eth-driver/src/error.rs
modules/anonify-eth-driver/src/eth/event_watcher.rs
modules/anonify-eth-driver/src/workflow.rs

* コントラクトでstate counterをインクリメント・イベント発火して、TEEノードでインクリメント検証
以下のケースで順序変わりうる可能性
* state-runtimeノードが受け取ってから状態に反映するまで（現状シングルスレッドなのでmaliciousな場合のみ）（merkle検証がないとstatecounterは改ざんできうる）

Implement a counter for enforcing the order of state transitions

---

.env.sample
Cargo.lock
nodes/state-runtime/server/src/lib.rs

- `.env` のコメントアウトを別行に修正（コメントも含めてparseされ、panicするため）
- typo修正

fix comment out in .env

---

nodes/key-vault/server/src/tests.rs
scripts/test.sh

- tests.shからkey-vaultのテストが一部しか実行されていなかったので、すべて実行されるように修正
- remoteの`path_secrets`は`clear_remote_path_secrets`によってファイルのみ削除される（ディレクトリは残る）ので、削除されたことのチェックロジックを変更

fix key vault tests

---

Cargo.lock
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands.rs
nodes/key-vault/Cargo.toml
nodes/key-vault/src/tests.rs
nodes/state-runtime/server/Cargo.toml
nodes/state-runtime/server/src/tests.rs

* 現状の `anonify_ecall_types::input::Command` をenclave専用型 `CommandPlaintext` にし、metafield含めた新たな型を共有型として使うために、結合テストで使用している `anonify_ecall_types::input::Command` をjsonで表現するよう修正
TODO
* 暗号文とメタデータinput用の型をecall-typesに定義
* 状態遷移API修正

結合テスト実装の`anonify_ecall_types::input::Command` をjsonで表現

---

Cargo.lock
frame/runtime/src/traits.rs
frame/sodium/src/crypto.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/enclave_key.rs
modules/anonify-enclave/src/notify.rs
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/workflow.rs
nodes/key-vault/src/tests.rs
nodes/state-runtime/api/Cargo.toml
nodes/state-runtime/api/src/lib.rs
nodes/state-runtime/server/Cargo.toml
nodes/state-runtime/server/src/handlers.rs
nodes/state-runtime/server/src/tests.rs
scripts/test.sh
tests/integration/src/lib.rs

POST: /state のリクエストボディを以下のように修正。（フラット化、user_idフィールド追加）
```
{ 	
"ciphertext": String
"ephemeral_public_key": String
"nonce": String
"user_id": String // optional
}
```
user_idフィールドが存在する場合は、`ciphertext` での平文jsonの `access_policy` から得られる `user_id` と一致しなければアクセスポリシー評価で失敗する。
user_idフィールドは存在しなくてもOK。

POST: state APIにおけるユーザID一致検証によるアクセスポリシー評価実装

---

Cargo.lock
example/erc20/cli/src/commands.rs
example/erc20/cli/src/main.rs
example/erc20/server/src/main.rs
modules/anonify-eth-driver/Cargo.toml
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/traits.rs
nodes/key-vault/src/tests.rs
nodes/state-runtime/api/src/lib.rs
nodes/state-runtime/server/src/handlers.rs
nodes/state-runtime/server/src/lib.rs
nodes/state-runtime/server/src/tests.rs

StateRuntimeノード起動時にBCの同期とjoin_groupトランザクションの送信。
TODO
* `'static` 、Server初期化重複は https://github.com/LayerXcom/anonify/issues/508 対応後外す
* healthcheck修正（https://github.com/LayerXcom/anonify/issues/510）
* https://github.com/LayerXcom/anonify/issues/509

BC同期、join_group自動化実装

---

Cargo.lock
modules/anonify-eth-driver/src/dispatcher.rs
nodes/state-runtime/server/src/handlers.rs
tests/integration/Cargo.toml
tests/integration/src/lib.rs

CMD定数は moduleレベルの `anonify-ecall-types` で定義されているので。
fixed: https://github.com/LayerXcom/anonify/issues/509

CMD定数をhandlerからではなくdispatcherから渡す

---

example/erc20/server/src/main.rs
modules/anonify-eth-driver/src/dispatcher.rs
nodes/key-vault/src/tests.rs
nodes/state-runtime/server/src/lib.rs
nodes/state-runtime/server/src/tests.rs

* `Dispatcher`内を `Arc`で持たせてcloneできるようにし、 `run()`時に 別スレッドにDispatcherがmoveしてしまうかつ `fetch_events`と`join_group`はimmutableなので、move前にclone()し返り値はselfを返す
* actix-webで `data()` に渡す引数は`Arc<>`である必要
fixed: https://github.com/LayerXcom/anonify/issues/513

サーバー初期化重複解消

---

Cargo.lock
ethereum/contracts/Anonify.sol
modules/anonify-ecall-types/src/lib.rs
modules/anonify-ecall-types/src/types.rs
modules/anonify-enclave/src/commands/treekem.rs
modules/anonify-enclave/src/handshake.rs
modules/anonify-eth-driver/src/dispatcher.rs
modules/anonify-eth-driver/src/error.rs
modules/anonify-eth-driver/src/eth/connection.rs
modules/anonify-eth-driver/src/eth/event_watcher.rs
modules/anonify-eth-driver/src/eth/sender.rs
modules/anonify-eth-driver/src/workflow.rs
nodes/state-runtime/server/src/handlers.rs
nodes/state-runtime/server/src/lib.rs
tests/integration/Cargo.toml
tests/integration/src/lib.rs

* dispatcherなどホストレイヤ共通化実装（enum使う）
* join_groupもenumで実装
TODO
* EnclaveKey用のコマンド追加（Enclave側）
文脈
* dispatcherレイヤは内部でenum使うなどで同じ型・同じmethodを利用
* 一番下層のconnectionレイヤでロジック分ける
* ハンドラは全てロジック実装しておいて、server mainレイヤで使うハンドラを分ける（treekemはhandshakeハンドラ使うけど、enclave keyでは使わない、など）

[命令暗号方式抽象化] ホストレイヤ実装

---

ethereum/contracts/AnonifyWithTreeKem.sol
example/erc20/enclave/src/state_transition.rs
modules/anonify-eth-driver/src/dispatcher.rs
nodes/state-runtime/server/src/tests.rs

- joinGroup、handshake時に全state-runtimeの`_groupKeyCounter`を更新するよう修正
- state-runtime1/2両方からの更新/状態取得のテストをCIに追加

fix joinGroup and update CI

---

frame/treekem/src/application.rs
modules/anonify-eth-driver/src/dispatcher.rs
nodes/key-vault/src/test/enclave_key.rs
nodes/key-vault/src/test/mod.rs
nodes/key-vault/src/test/treekem.rs
nodes/state-runtime/server/src/handlers.rs
nodes/state-runtime/server/src/lib.rs
nodes/state-runtime/server/src/test/enclave_key.rs
nodes/state-runtime/server/src/test/mod.rs
nodes/state-runtime/server/src/test/treekem.rs
scripts/test.sh
tests/integration/src/enclave_key.rs
tests/integration/src/treekem.rs
tests/units/enclave/src/lib.rs

fix: #453 
- エラーメッセージの具体化（例: `ERROR`→`A event is skipped because of occurring error in enclave`）※
- 正常系のテストには`ERROR`が含まれて *いない* ことを確認
- `get_state`内で`fetch_event`するのをやめた→`delay_for`ｄ
- typo修正
※enclave内のエラーはtracingで取れないので未対応

エラーログをCIでチェック

---

frame/config/src/lib.rs

（なし）
VSCode の Remote Container で dev環境上のコンテナに接続し、rust-analyzer をかけていたところ、たまたまtitleの問題に気づきました。
考えられるfeatureの組み合わせで、CIでマトリクスビルドを書けておくべきだと思います。
今回はやらないですが、このPRが妥当と判断されたらまずはissue化します。
rust-analyzer がエラーを吐かなくなった
（なし）

fix: `feature = ["sgx", "std"]` のケースで `localstd` が二重定義される問題を修正

---

scripts/test.sh

* CIからazure clientユニットテストを一時的に削除
* #603 （azure clientテスト復活）
* リトライを追加しても決定的にazuriteへのリクエスト時に失敗してしまう。（CI環境 only）
* エラーメッセージが `No route to host` なのでtcp connectionそもそもできていない。
* 他PRを優先させるため一時的にユニットテスト削除。

CIからazure clientユニットテストを一時的に削除

---

.gitignore

（なし）
.gitignore 追記。
開発環境のdocker containerにVSCodeのRemote Container機能を使って接続して開発しているため、
コンテナの中にはいつも自分が使っている `~/.gitignore` がなく、
```json
{
"cSpell.words": [
"Ecall",
"Encinteger"
]
}
```
のような中身の `.vscode/settings.json` が毎回git操作で出てきて邪魔になるので。
（なし）
コンテナ内の操作で
>  `.vscode/settings.json` が毎回git操作で出てきて
が解消。
（なし）

chore: ignore `.vscode/`

---

example/erc20/enclave/src/ecalls.rs
example/key-vault/enclave/src/ecalls.rs
frame/enclave/src/engine.rs
frame/enclave/src/engine/basic_enclave_engine.rs
frame/enclave/src/engine/state_runtime_enclave_engine.rs
frame/enclave/src/register.rs
modules/anonify-enclave/src/backup.rs
modules/anonify-enclave/src/commands/enclave_key.rs
modules/anonify-enclave/src/commands/treekem.rs
modules/anonify-enclave/src/context.rs
modules/anonify-enclave/src/enclave_key.rs
modules/anonify-enclave/src/handshake.rs
modules/anonify-enclave/src/join_group/enclave_key.rs
modules/anonify-enclave/src/join_group/treekem.rs
modules/anonify-enclave/src/notify.rs
modules/key-vault-enclave/src/server.rs

（なし）
- EnclaveEngine、runtimeに依存する版（StateRuntimeEnclaveEngine）としない版（BasicEnclaveEngine）にtraitを分けた
- 元々 `handle()` と `handle_without_runtime()` が混ざった、使い方に注意が必要なtraitであった
- `BasicEnclaveEngine::handle` は self 引数を取り、 ecall_input が取得できるようにした
- `EnclaveEngine::decrypt` は実際には復号していないコンストラクタなので、 `new` と改名
（なし）
コンパイル・テスト通ればOK
これから暗号DBを作るに当たり、enclave_inputを取る & runtimeに依存しないEnclaveEngineが必要だったので、先に作りました。

refactor: EnclaveEngine、runtimeに依存する版としない版のtraitを分けた & しない版の handle() において ecall_input を引数から取得できるようにした

---

Cargo.lock
example/erc20/enclave/src/ecalls.rs
example/key-vault/enclave/src/ecalls.rs
frame/common/src/state_types.rs
frame/enclave/src/register.rs
frame/host/src/ecalls.rs
frame/host/src/engine.rs
modules/anonify-eth-driver/src/workflow.rs
modules/key-vault-host/src/workflow.rs

* https://github.com/LayerXcom/anonify/issues/463
ホストから任意長のデータサイズをecallのバッファに許可してしまうとプロセスが落ちる。 serialize時にバイト数を制限し、エラーハンドリングを実施。
```rust
let input_payload = bincode::DefaultOptions::new()
.with_limit(self.ecall_max_size as u64)
.serialize(&input)?;
```

ecall時の最大バイト数を`bincode`で制限することでエラーハンドリング

---

scripts/Makefile
scripts/test.sh

* なし
* unused variablesの削除
* targetとする生成物が、変数名からわかるようにrename
* 標準出力と生成ファイルが一致するよう修正
* 依存関係の整理
* なし
* CI
* `prd-signed.so`を含んだ検証として`example-erc20.Dockerfile`がdocker buildできることを手動で確認
依存関係の整理について補足です。
処理の中で必要なものが`:`の右に来るようにしています。
例外は`T_O_FILE`の生成で、処理で明示される`T_C_FILE`が`Enclave_EDL_Files`の最初の値というのがトリッキーです。
これは標準出力と生成ファイルが一致するようにする方針を優先して例外としています。

fix Makefile

---

.env.sample
docker/base-rust-sgx-sdk-rootless.Dockerfile
docker/entrypoint/fixuid.bash

（なし）
fixuid が遅すぎること（[20分たっても完了しなかった例](https://dev.azure.com/osukesudo/Anonify/_build/results?buildId=1901&view=logs&j=c3a[…]-53c8-4801-c97d6d711cc0&t=5a7e4c1e-bc5c-5f38-dfcb-a0ac47d5b0f3)）に端を発し、
- `/home/anonify-dev/` 以下のみを chown 対象にすることで若干の高速化（とはいえこれだけではまだまだ遅いこと把握してる）
- `FIXUID_MODE=verbose` を新設し、遅くてもせめて「何のchownが進行しているか」がわかるようにした
本当に必要なレベルの高速化。もしかしたら chown する機能は fixuid に頼らず `chown -R ~/` とかするようにしたほうがいいのかもしれないと考えてる 🤔 
```bash
docker build -t anonify.azurecr.io/rust-sgx-sdk-rootless:latest --file docker/base-rust-sgx-sdk-rootless.Dockerfile .
docker run  --env-file .env -u `id -u`:`id -g` -v `pwd`:/home/anonify-dev/anonify --rm -it anonify.azurecr.io/rust-sgx-sdk-rootless:latest
```
これで `skip`, `quiet`, `verbose` のモードが期待通りに動くことと、 `skippp` のような無効なパラメータを渡すと警告が出ること確認。
（なし）

feat: fixuidの遅さ・使い勝手改善

---

docker/base-anonify-dev.Dockerfile
docker/base-rust-sgx-sdk-rootless.Dockerfile
docker/entrypoint/fixuid.bash

（なし）
```bash
docker run -it anonify.azurecr.io/rust-sgx-sdk-rootless:latest bash -c 'echo hi'
```
など実行しても、 ( `-it` パラメータありなら）インタラクティブシェルログインされるだけで、echoの実行がされない問題があった。
デフォルトでbashなインタラクティブシェルログインされる挙動は残しつつ、コマンドを自由に上書きできるように修正。
（なし）
上述のコマンドなど
https://docs.docker.jp/engine/reference/builder.html#exec-entrypoint このへんでも紹介されてるテクです。

fix: ENTRYPOINT においてインタラクティブシェルを立ち上げていたので、`docker run` の最終引数のコマンドや、 `docker-compose exec` の際のyamlの `command:` が実行されていなかった

---

azure-pipelines.yml
docker/example-encrypted-sql-ops-pg.Dockerfile
docker/example-erc20.Dockerfile
docker/example-keyvault.Dockerfile
e2e-docker-compose.yml
scripts/e2e-test.sh

（なし）
Dockerイメージのrootlessなど諸々やっていた結果、E2Eテストが動かなくなっていたので修正。
- `/home-anonify-dev/anonify` という嘘pathの修正
- docker build で作られる各種ファイルの owner が anonify-dev になるよう調整
あたりが本質的な差分です。
（なし）
E2EのstepがCI上成功していることは確認しています。
**念の為、CIのログを見てE2Eが正常動作していることを確認してほしい** です。
（なし）

ci: E2Eテストが壊れていたので修正

---

azure-pipelines.yml

* なし
* docker image pruneが複数agentかつ同一VMで同時実行されるとlockされていてエラーが起きるので、各stageの末尾でdependsOnした上で実行されるよう修正
* なし
* CI
* mianはマージするまで実行されないので未検証（PR承認後のマージで動作確認予定）
* 前提として同一VMでないと機能しないfixになってしまっている

execute docker image prune as a dependsOn job

---

azure-pipelines.yml
templates/check_changes_of_base_dockerfile.yml
templates/setup_env.yml

* なし
- pgxを通常CIから分離
- mainマージ時に通常CI、e2e CI、pgx CI追加
- base-*をbuildするのはDockerfileに変更があった場合のみ
- base-*の隠蔽をtemplate化
- SPIDとSUB_KEYは必要なtaskにてenvで設定
- なし
* CI
* mainマージは例によって未確認
* なし

CI improvements

---

Cargo.lock

* なし
* `serde_bytes` (SGX) がupdateされたせいで、CIがコケる（localでもコンパイルできなくなってるはず）ので、修正
* なし
* CI
* [対応手順](https://www.notion.so/failed-to-load-source-for-dependency-bb77ddb2f246449fb697da026679f1df)

update serde_bytes to fix version error

---

config/Enclave.config.xml
frame/mra-tls/Cargo.toml
frame/mra-tls/src/verifier.rs
frame/runtime/Cargo.toml
frame/treekem/Cargo.toml
modules/anonify-enclave/Cargo.toml

* なし
* `verify-mr-enclave-enable`フィーチャーフラグを追加し、有効な場合のみMRENCLAVEの一致検証を行うように修正
* `verify_measurement`メソッドを`verify_mr_enclave`と`verify_mr_signer`に分割
* `verify-mr-enclave-enable`はデフォで有効になっている
* 特になし
* test.shで動作確認
* 特になし

features指定でMRENCLAVEの一致検証を行うように修正

---

frame/azure-client/src/blob.rs

* なし
* blob名をリストアップする関数を追加
* なし
* CI
* 手動で指定したcontainerに含まれるblobの一覧が取得できることを確認
* なし

implement list for azue-client

---

frame/azure-client/src/blob.rs

* なし
* blobデータを取得する際、途中までしか取得できないため、取得処理のrangeを1024から2048に変更
* なし
* 別のリポジトリにて動作確認済
* なし

fix range for BlobClient's get method
